// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Empty = Caml_exceptions.create("Stack-Datastructure.Empty");

function create(param) {
  return /* record */[
          /* c : [] */0,
          /* len */0
        ];
}

function push(x, s) {
  return /* record */[
          /* c : :: */[
            x,
            s[/* c */0]
          ],
          /* len */List.length(s[/* c */0])
        ];
}

function pop(s) {
  var match = s[/* c */0];
  if (match) {
    s[/* c */0] = match[1];
    s[/* len */1] = s[/* len */1] - 1 | 0;
    return match[0];
  } else {
    throw Empty;
  }
}

function popOpt(s) {
  var match = s[/* c */0];
  if (match) {
    s[/* c */0] = match[1];
    s[/* len */1] = s[/* len */1] - 1 | 0;
    return Caml_option.some(match[0]);
  }
  
}

function top(s) {
  var match = s[/* c */0];
  if (match) {
    return match[0];
  } else {
    throw Empty;
  }
}

function topOpt(s) {
  var match = s[/* c */0];
  if (match) {
    return Caml_option.some(match[0]);
  }
  
}

function clear(s) {
  s[/* c */0] = /* [] */0;
  s[/* len */1] = 0;
  return /* () */0;
}

function copy(s) {
  return /* record */[
          /* c */s[/* c */0],
          /* len */s[/* len */1]
        ];
}

function isEmpty(s) {
  var match = s[/* c */0];
  if (match) {
    return true;
  } else {
    return false;
  }
}

function length(s) {
  return s[/* len */1];
}

function iter(fn, s) {
  return List.iter(fn, s[/* c */0]);
}

function fold(fn, acc, s) {
  return List.fold_left(fn, acc, s[/* c */0]);
}

var Stack = /* module */[
  /* create */create,
  /* push */push,
  /* pop */pop,
  /* popOpt */popOpt,
  /* top */top,
  /* topOpt */topOpt,
  /* clear */clear,
  /* copy */copy,
  /* isEmpty */isEmpty,
  /* length */length,
  /* iter */iter,
  /* fold */fold
];

exports.Empty = Empty;
exports.Stack = Stack;
/* No side effect */
